name: alien-arena-linux # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '7.71.6' # just for humans, typically '1.2+git' or '1.3.2'
summary:  Ultra Fast-Paced Arena FPS
description: |
   Do you like old school deathmatch with modern features? How about rich, colorful, arcade-like atmospheres? How about...retro Sci Fi? Then you're going to love what Alien Arena has in store for you! This game combines some of the very best aspects of such games as Quake III and Unreal Tournament and wraps them up with a retro alien theme, while adding tons of original ideas to make the game quite unique.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  alienarena_icon.png
title: Alien Arena

apps:
  alienarena:
    command: bin/alienarena
parts:
  alienarena:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      alienarena: build/
      alienarena.1: man/man1/

architectures:
  - build-on: amd64

